### PR TITLE
update om_display for vtk6 (will not work on vtk 5, now)

### PR DESCRIPTION
**Pull request by eolivi**
BTW @agramfort  can you please tell me how can one run the tests doing: `python setup.py test`
In the setup.py there should be a test_suite argument no ? then how ?

### CODE REVIEW

**Comment by agramfort** [comment]
I use 

nosetests openmeeg_viz

to run the tests

**Comment by agramfort** [comment]
besides LGTM

**Comment by eolivi** [comment]
OK for nosetests... thanks !
I added a test for om_display as suggested. but it needs human interaction (to exit the display mode 'press q').
For the other test on_viz, I get a segfault ...

**Comment by agramfort** [comment]
there are ways to have a non-blocking vtk window. Mayavi can do this. Look for offscreen rendering.

for segfault I don't know...

**Pull request merged**
